language: d
d:
  - dmd
  - dmd-beta
  - dmd-nightly
  - ldc
  - ldc-beta

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
